import requests
from bs4 import BeautifulSoup
from pathlib import Path
import re

def _google_images_search(search_term):
    """
    Improved Google Images search: extract image URLs from HTML and embedded JSON.
    """
    try:
        api_url = "https://www.google.com/search"
        params = {
            'q': search_term,
            'tbm': 'isch',
            'hl': 'en',
            'ijn': '0'
        }
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'DNT': '1',
            'Connection': 'keep-alive',
        }
        response = requests.get(api_url, params=params, headers=headers, timeout=15)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')

        # 1. Try to get images from <img> tags
        images = []
        for img in soup.find_all('img'):
            src = img.get('src') or img.get('data-src')
            if src and src.startswith('http'):
                images.append(src)

        # 2. Try to extract image URLs from embedded JSON in <script> tags
        for script in soup.find_all('script'):
            if 'AF_initDataCallback' in script.text:
                # Find all URLs ending with image extensions
                urls = re.findall(r'"(https://[^"]+\.(?:png|jpg|jpeg|webp))"', script.text)
                images.extend(urls)

        # Remove duplicates while preserving order
        seen = set()
        images = [x for x in images if not (x in seen or seen.add(x))]

        # Prefer PNGs, then any image
        for img_url in images:
            if 'logo' in img_url.lower() and img_url.lower().endswith('.png'):
                return img_url
        for img_url in images:
            if img_url.lower().endswith('.png'):
                return img_url
        for img_url in images:
            if 'logo' in img_url.lower():
                return img_url
        return images[0] if images else None

    except Exception as e:
        print(f"Google images search error: {e}")
        return None

def _download_image(image_url, folder_path, filename="logo.png"):
    """
    Download the image and save it to the specified folder with the given filename.
    """
    try:
        response = requests.get(image_url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}, timeout=15)
        response.raise_for_status()
        
        # Check if it's actually an image
        if 'image' not in response.headers.get('content-type', ''):
            print(f"URL was not an image: {image_url}")
            return False
        
        # Save the image
        logo_path = Path(folder_path) / filename
        with open(logo_path, 'wb') as f:
            f.write(response.content)
        
        return True
        
    except Exception as e:
        print(f"Download error: {e}")
        return False

if __name__ == "__main__":
    base_path = Path("output")
    
    if not base_path.exists():
        print(f"Directory 'output' does not exist!")
    else:
        # Find all JSON data files generated by the previous script
        json_files = list(base_path.glob("*_data.json"))
        print(f"Found {len(json_files)} company profiles in {base_path}")
        
        for json_file in json_files:
            # Extract company name from filename (e.g., "Microsoft_data.json" -> "Microsoft")
            safe_name = json_file.stem.replace('_data', '')
            company_name_search = safe_name.replace('_', ' ')
            
            # Define specific filename for this company (e.g., "Microsoft_logo.png")
            # This allows multiple logos to exist in the flat output folder
            target_filename = f"{safe_name}_logo.png"
            target_path = base_path / target_filename
            
            if target_path.exists():
                print(f"✓ Logo already exists for {company_name_search}")
                continue

            print(f"Processing: {company_name_search}...")
            
            # search logic
            image_url = _google_images_search(f"{company_name_search} logo")
            
            if image_url:
                success = _download_image(image_url, base_path, filename=target_filename)
                if success:
                    print(f"  ✓ Downloaded {target_filename}")
                else:
                    print(f"  ✗ Failed to download")
            else:
                print(f"  ✗ No image found")